@echo off
echo Creating virtual environment...
python3 -m venv venv
echo Activating venv...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn app.main:app --reload --port 8000
